### ISSUE TITLE
Template sources

### ISSUE THREAD

**Issue by tonglil** [hairyhenderson/gomplate#1291] opened 2022-01-26 00:43 UTC
Is it possible to source a template from a remote source, it `https://` instead of a local file?

Currently I'm using `curl` and stdin, but it would be nice to be able to use [config files](https://docs.gomplate.ca/config/) and specify urls in it directly under `templates` and `in` for example.

```
curl -s https://url/template.file | gomplate -f -
```
to
```
gomplate -f https://url/template.file
```

**Comment by hairyhenderson** [comment] 2022-01-27 00:50
Hi @tonglil - this is actually something that I'm (slowly) working towards - there's a similar request in #963. Thanks for filing this though, as it's reminded me that this is work that people are still interested in!

**Comment by hairyhenderson** [comment] 2022-02-05 14:26
I think this is actually a duplicate of #963 - I just realized #1125 is currently open (though has been stalled for a while) to solve it. This will likely be part of gomplate v4.

**Closed by hairyhenderson** 2022-02-05 14:26 UTC
Labels: duplicate
