### ISSUE TITLE
gomplate in Caddy

### ISSUE THREAD

**Issue by rayjlinden** [hairyhenderson/gomplate#941] opened 2020-09-09 04:34 UTC
I saw you wrote the little "I am a teapot" example in Caddy.  Made me chuckle!

What I would love to see is Caddy's template system support your Datasource functions.  (Hell a bunch of your other functions would make their system nicer as well).  I was thinking it would be cool if you had a Caddfile that did something like

templates {
    datasource <name> <url or path to file>
}

Then that data source would be available in the Caddy templating system.  (Via something like your datasource function.  Actually, with defineDatasource you don't even need the tweak to the Caddyfile.)  

I know this idea doesn't belong here.  But I thought you might find the idea kind of cool if your own interest in Caddy was anything more than passing...

**Comment by hairyhenderson** [comment] 2020-09-09 15:12
Hmm! Thanks for logging this, @rayjlinden!

Indeed I do have an interest in Caddy (I'm the maintainer for [official `caddy` Docker image](https://hub.docker.com/_/caddy) 😉). However I'm still shamefully novice on the core functionality of Caddy itself (something I'm working slowly on remedying!). All that to say, I don't have a deep enough understanding of Caddy's template system and its goals to know whether or not gomplate integration makes sense.

It might certainly be interesting, as you say, to support datasources in templates - that's IMO one of gomplate's great strengths. And it could be interesting to add support for some of gomplate's functions in addition to the sprig functions that are already supported - there's a lot of overlap though, and not all compatible.

What I _do_ know is that using `text/template` for producing HTML isn't always the safest thing ([`html/template`](https://golang.org/pkg/html/template/) should be used instead). This is what gomplate is (by design) using, and I see that Caddy also uses it (I'm curious why not `html/template`?)... Though it all depends on what kind of user-input is allowed.

Paging @mholt, @francislavoie and/or @Mohammed90 for further ideas 😉

**Comment by mholt** [comment] 2020-09-09 15:26
We use text/template in Caddy's `template` middleware because we _want_ to write actual HTML content to the response, not HTML-escaped content. There are functions to escape untrusted values within your template, but the whole point of our middleware is to be able to write unescaped content so browsers will render it.

**Comment by rayjlinden** [comment] 2020-09-09 15:42
I noticed they used text/template as well.  I was not aware there are
"safety" issues.  What are those exactly?

I'm just getting into Caddy myself - just started working on an S3 proxy
(for when it is not cool/safe to make the S3 bucket a public web site.).
The documentation of Caddy could use a lot more detail that's for sure...
I have some of the same questions about some of the goals for some of the
directives they support.

For example, I was wondering if it would be easy to just fork the
templating (and call it gomplates or something :) to add additional
template functions, etc.  However, it is unclear to me how "built-in" the
templates directive is vs. other directives.  Is it even possible to do
what the templates directive is doing without being part of the core?  If
you can't tell, I'm very much hinting that I think with the gomplate core
you could provide a much better and more powerful templates directive than
the current one!  :)

Ray

**Comment by hairyhenderson** [comment] 2020-09-09 15:51
> I was not aware there are "safety" issues. What are those exactly?

It's just that `html/template` processes HTML as well and does some escaping. The [docs](https://golang.org/pkg/html/template/) explain it. In Caddy, I agree it's not really necessary - the key is to be sure that you trust your template and the data that goes into it.

It's more that if you're doing HTML templating in a server and you don't understand the risks and nuances, you should choose `html/template` by default. But `text/template` (and thus Caddy and gomplate) has the `html` and `js` and `urlquery` functions which you can _mostly_ use to provide the same safety when you're dealing with untrusted input.

> The documentation of Caddy could use a lot more detail that's for sure...

It's definitely worth bringing up missing detail in the Caddy forum and/or logging issues in the Caddy repo for that - if you're not aware of the forum it's at https://caddy.community/ and is full of some _super_ useful info. There's a Wiki there too with some more stuff that doesn't really belong in the docs.

> Is it even possible to do what the templates directive is doing without being part of the core?

I _believe_ so? I'm chatting with @mholt and @francislavoie in our super-secret Caddy maintainers chat right now 😉

Ultimately I think the first place to start would be by creating an out-of-core Caddy module based on the current `templates` module. You could simply copy https://github.com/caddyserver/caddy/tree/master/modules/caddyhttp/templates and start there - it doesn't import anything internal so it should be usable outside of the core.

If this is something you're interested/able to do, please go ahead! I'm not sure I have the time to commit to this just yet 😅

**Comment by hairyhenderson** [comment] 2022-06-19 23:07
Not sure if there's anything to be done here, so I'm going to close this. If there's more to discuss feel free to re-open, or open a [discussion](https://github.com/hairyhenderson/gomplate/discussions)!

**Closed by hairyhenderson** 2022-06-19 23:07 UTC

**Comment by francislavoie** [comment] 2022-06-19 23:28
Worth mentioning that Caddy's `template` module gained the ability to be extensible/pluggable, allowing additional templating functions to be added to the template context https://github.com/caddyserver/caddy/pull/4757. This might be useful is someone wants to provide many of gomplate's features as a plugin 🤷‍♂️
