### ISSUE TITLE
gomplate --version: 0.0.0

### ISSUE THREAD

**Issue by Noah-Huppert** [hairyhenderson/gomplate#188] opened 2017-08-03 20:06 UTC
If you install gomplate via:

```
$ go get github.com/hairyhenderson/gomplate
```

and then run:

```
$ gomplate --version
```

It will output:

```
$ gomplate --version
gomplate version 0.0.0
```

Saying the current version is `0.0.0`. I believe the latest relieve is `1.10.0`?

**Comment by hairyhenderson** [comment] 2017-08-03 20:19
@Noah-Huppert this is expected - the version number is inferred from the git tag during the `make build` process.

Is there a particular reason you're installing with `go get`?

**Comment by Noah-Huppert** [comment] 2017-08-03 21:37
Yea, 1 command vs 3 or 4

**Comment by hairyhenderson** [comment] 2017-08-03 23:42
Ah, makes sense!

I'll close this for now since this is expected behaviour.

**Closed by hairyhenderson** 2017-08-03 23:42 UTC
