### ISSUE TITLE
ignore templating to the line if comment exist

### ISSUE THREAD

**Issue by dorsany** [hairyhenderson/gomplate#541] opened 2019-04-17 09:32 UTC
I'm trying to ignore templating lines with comment in my ```yml``` files, but I couldn't find a way to do it

The reason is because sometimes we have a loop of a line (like mention below) which is not 
comment followed be the line that it started from

**For Example:** 

I have a file with the following content:

```
# spec:
#   externalIPs:
#{{ if (datasource "myenv").OVERRIDE_BIND_ADDRESS }}    - {{ (datasource "myenv").OVERRIDE_BIND_ADDRESS }}{{ printf "\n  "}}{{ else }}{{ range (sockaddr.GetPrivateInterfaces | sockaddr.Include "type" "ipv4" | sockaddr.Include "name" "(^en.+|^eth.+)") }}{{ printf "    - %s\n" (. | sockaddr.Attr "address") }}{{ end -}}{{ printf "  "}}{{ end -}}
#   type: LoadBalancer

```

and after templating the above file:

```
# spec:
#   externalIPs:
#    - 192.168.50.226
    - 192.168.1.112
  #   type: LoadBalancer

```

in my case the line ```- 192.168.1.112``` cause to kubectl issues

any idea of how to solve this kind of issue?

**Comment by hairyhenderson** [comment] 2019-04-17 12:54
Hi @dorsany, thanks for logging this! gomplate doesn't care about YAML comments - the input template is always treated as plain text.

You can use the `{{/* */}}` format to comment things out in templates.

**Comment by dorsany** [comment] 2019-04-17 17:00
Hi @hairyhenderson , maybe it can be a feature request?

Just a suggestion, new flag (like ``` --ignore-comment ````)  and if you add this flag to gomplate will check each line that starts with ```#``` or ```//```` or ```/*``` and it will skip that line and it won't template it?

**Comment by hairyhenderson** [comment] 2019-04-18 00:04
gomplate isn't primarily intended for templating YAML, although that seems to be a popular usage! It's also not aware of _any_ particular syntax in templates other than the Go templating syntax, so it would be quite difficult (and IMO the wrong approach) to have it understand comments from other syntaxes.

If your intent is to temporarily get gomplate to ignore the section, here's one way to do it:

```yaml
# spec:
#   externalIPs:
{{- /*
#{{ if (datasource "myenv").OVERRIDE_BIND_ADDRESS }}    - {{ (datasource "myenv").OVERRIDE_BIND_ADDRESS }}{{ printf "\n  "}}{{ else }}{{ range (sockaddr.GetPrivateInterfaces | sockaddr.Include "type" "ipv4" | sockaddr.Include "name" "(^en.+|^eth.+)") }}{{ printf "    - %s\n" (. | sockaddr.Attr "address") }}{{ end -}}{{ printf "  "}}{{ end -}}
*/ -}}
#   type: LoadBalancer
```

There may be a better way to accomplish what you're looking for though. Can you perhaps clarify exactly what the issue is?

**Comment by dorsany** [comment] 2019-04-18 12:50
Hi @hairyhenderson ,  Thank you for your answer!

My issue is that the gomplate is creating for me a new line (as expected) without a comment

like here:
```
# spec:
#   externalIPs:
#    - 192.168.50.226
    - 192.168.1.112
  #   type: LoadBalancer
```

but I need to get file (after templating it) like that:

```
# spec:
#   externalIPs:
#    - 192.168.50.226
#    - 192.168.1.112
  #   type: LoadBalancer
```
or like that:
```
# spec:
#   externalIPs:
#{{ if (datasource "myenv").OVERRIDE_BIND_ADDRESS }}    - {{ (datasource "myenv").OVERRIDE_BIND_ADDRESS }}{{ printf "\n  "}}{{ else }}{{ range (sockaddr.GetPrivateInterfaces | sockaddr.Include "type" "ipv4" | sockaddr.Include "name" "(^en.+|^eth.+)") }}{{ printf "    - %s\n" (. | sockaddr.Attr "address") }}{{ end -}}{{ printf "  "}}{{ end -}}
#   type: LoadBalancer
```


but from your answer above I can understand that this is not possible to do

Tanks anyway!

**Comment by hairyhenderson** [comment] 2019-04-19 00:31
If you add the `#` into the `printf` arg as `printf "#    - %s\n"` then it'll work, but that's probably not entirely what you want either...

I'll close this issue for now - but feel free to re-open if you have more questions around this 🙂

**Closed by hairyhenderson** 2019-04-19 00:31 UTC
